### ISSUE TITLE
Error while converting rsf file to numpy

### ISSUE THREAD

**Issue by tgautam03** [ahay/src#187]
I'm using the following code to convert rsf file to numpy 
```
import m8r 
import numpy as np
import matplotlib.pyplot as plt
inp = m8r.Input("vel.rsf")
n1 = inp.int("n1")
n2 = inp.int("n2")
 
data =inp.read(shape=(n2,n1))
data = data.transpose() # Example of numpy in action
print("SHAPE OF ARRAY : ", data.shape)
print("MAX VEL : ", np.max(data))
print("MIN VEL : ", np.min(data))
#print("UNIQUE VELS : ", np.unique(data))
np.save('pvel.npy', data)
plt.imshow(data)
plt.show()
```
and I'm getting the following error 
```
Traceback (most recent call last):
  File "model.py", line 4, in <module>
    inp = m8r.Input("vel.rsf")
  File "/home/tushar/rsf2.0/lib/python3.7/site-packages/m8r.py", line 720, in __init__
    self.f = open(self.filename,'r')
FileNotFoundError: [Errno 2] No such file or directory: '"/var/tmp/mdg/2D_modeling/marmousi2mp/vel.rsf@"'
```

**Comment by sfomel** [comment]
What output do you get when you run "sfin vel.rsf" on the command line?

**Comment by deckerla** [comment]
I encountered this bug today in a similar situation.
```
inp = m8r.Input(exdir+'/%s'%filelst[0])
```
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-24-10581a1a149f> in <module>
----> 1 inp = m8r.Input(exdir+'/%s'%filelst[0])

~/RSFROOT/lib/python3.6/site-packages/m8r.py in __init__(self, tag)
    718                 self.f.close()  # close input file is not stdin
    719                 self.filename=self.string("in")
--> 720                 self.f = open(self.filename,'r')
    721 
    722             # need to remember fileloc of beginning of data

FileNotFoundError: [Errno 2] No such file or directory: '"/var/tmp/scratch/traces/trace-0-0-0-0-0-0.rsf@"'
```

Manually removing the " " around the in="/$DATAPATH/datadir" line of the .rsf header file enabled m8r to locate the input file, but then it threw a different error:

```
error reading from input file.
data_format="native_float"
filename=/var/tmp/scratch/traces/trace-0-0-0-0-0-0.rsf@.
data_format must be native_float, native_complex or native_int
error - exiting program
error reading from input file.
data_format is not defined
filename=/var/tmp/scratch/traces/trace-0-0-0-0-0-0.rsf@.
error - exiting program
```

This makes it seem like the issue has to do with the use of "" in the .rsf header file.

**Comment by deckerla** [comment]
I was able to overcome these issues by making sure SWIG was installed on my computer, uninstalling and reinstalling scons, and then reconfiguring and reinstalling Madagascar.

If you are not able to install swig, it seems like a fix to make the non-swig version more compliant could be inserting the following code into $RSFSRC/lib/python3.7/site-packages/m8r.py 

currently at line ~ 718 you have the following:
```
                self.filename=self.string("in")
                self.f = open(self.filename,'r')
```

You could insert a translate command to remove unwanted " and ' from the file name string:
```
                self.filename=self.string("in")
                # strip quotation marks
                self.filename=self.filename.translate({ord(i):None for i in '\"\''})
                self.f = open(self.filename,'r')
```

This process could be repeated for the data_format line around  at line ~736:
```
                data_format=self.vd['data_format']
                if data_format=='native_float':
                    self.type='float'
                    self.form='native'
                    esize=4
                    self.datatype=np.float32
```

Could become 

```
                data_format=self.vd['data_format']
                # strip unneded characters
                data_format.translate({ord(i):None for i in '\"\''})
                if data_format=='native_float':
                    self.type='float'
                    self.form='native'
                    esize=4
                    self.datatype=np.float32
```
