### ISSUE TITLE
Cannot read rsf file using m8r.Input() or m8r.File()

### ISSUE THREAD

**Issue by returncode13** [ahay/src#205]
:bug:  Bug report

**Unable to read an rsf file using the m8r library**

I am trying to read in vp.rsf which is created when the [marmousi SConstruct](https://github.com/ahay/src/blob/master/book/data/marmousi2/model/SConstruct) file is run

**To Reproduce**

1. run the marmousi [scons](https://github.com/ahay/src/blob/master/book/data/marmousi2/model/SConstruct)  
2. next run the following minimal code to replicate the error

```

import m8r
inp  = m8r.File('vp.rsf')
inp[:]
```

3. Error produced
```
Exception ignored in: <bound method File.__del__ of <m8r.File object at 0x7f8911a59278>>
Traceback (most recent call last):
  File "/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py", line 495, in __del__
    self.close()
  File "/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py", line 493, in close
    Filter('rm',run=True)(0,self)
  File "/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py", line 1466, in __call__
    self.setcommand(kw,args[1:])
  File "/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py", line 1425, in setcommand
    ' '.join(map(str,args)),
  File "/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py", line 278, in __str__
    if self.tag:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-43-d47f90bc4aa3> in <module>
----> 1 inp[:]

/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py in __getitem__(self, i)
    387     def __getitem__(self,i):
    388         #sys.stderr.write('in __getitem__n')
--> 389         array = self.__array__()
    390         return array[i]
    391     def __setitem__(self,index,value):

/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py in __array__(self, context)
    368                 # gets only the real part of complex arrays ##kls
    369 
--> 370                 f=Input(self.filename)
    371 
    372                 if False: #change to  'if True' to get this diagnostic print

/mnt/data/bin/madagascar-root/lib/python2.7/dist-packages/m8r.py in __init__(self, tag)
    718                 self.f.close()  # close input file is not stdin
    719                 self.filename=self.string("in")
--> 720                 self.f = open(self.filename,'r')
    721 
    722             # need to remember fileloc of beginning of data

FileNotFoundError: [Errno 2] No such file or directory: '"/var/tmp/data/marmousi2/model/vp.rsf@"'
```

I have checked for this file under `/var/tmp`  
and as you can see below, it exists but is reported as a `FileNotFoundError`
`rw-rw-r-- 1 sharath sharath 152385604 Jun 19 11:04 '/var/tmp/data/marmousi2/model/vp.rsf@'`

**System info :**  
output to `lsb_release -a`  
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by ofmla** [comment]
I am experiencing the same problem. It seems that the change in https://github.com/ahay/src/commit/67a1d151113f5be4c54f01b3a7244483cbd35ede to address the issue https://github.com/ahay/src/issues/176 is the cause of the problem.
