### ISSUE TITLE
Cannot save eps images with vpconvert

### ISSUE THREAD

**Issue by Xiaokui824** [ahay/src#284]
Install OS: Ubuntu(Virtual Machine) in MacOS 13 M-chip
Madagascar Version: 4.0
Python Version: 3.10.6
****************************

Bug:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 20: invalid start byte

Print:
Traceback (most recent call last):
  File "/home/parallels/Software/Mdagascar/Mdagascar/bin/vpconvert", line 223, in <module>
    convert(infile,outfile,format,pen,args)
  File "/home/parallels/Software/Mdagascar/Mdagascar/bin/vpconvert", line 128, in convert
    rsf.vplot2eps.convert(vpl,out,
  File "/home/parallels/Software/Mdagascar/Mdagascar/lib/python3.10/site-packages/rsf/vplot2eps.py", line 44, in convert
    head = out.read().split()
  File "/usr/lib/python3.10/codecs.py", line 323, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 20: invalid start byte

**Comment by sfomel** [comment]
I cannot reproduce this problem. It might be related to the particular image you are trying to convert. Can you share your vpl file?

**Comment by sfomel** [comment]
To keep the plot in color, run vpconvert with the color=y option. For other available options, see https://reproducibility.org/RSF/sfpspen.html

**Comment by Xiaokui824** [comment]
Dear Professor，

  Your answer has solved all my problems.
  Thank you very much for your help！
