### ISSUE TITLE
[BUG]Can't install Madagascar4.0 in Ubuntu 22.04

### ISSUE THREAD

**Issue by zhangxiaoshuotttt** [ahay/src#286]
:bug:  Bug report

**Description of the bug**

When I run "`Make`", it will give me an error , I think this is because my enviroment is not properly configured. 

**To Reproduce**

Here is my installation process:
1.  `./configure --prefix=$HOME`
```
checking for Python ... /home/master/anaconda3/bin/python
checking Python version ... 3.9.13
checking for RSFROOT ... /home/master
checking for SCons ... /home/master/anaconda3/bin/scons
checking SCons version ... v4.4.0.fc8d0ec215ee6cba8bc158ad40c099be0b598297
Running RSFROOT=/home/master /home/master/anaconda3/bin/scons  config ...
------------------------
scons: Reading SConscript files ...
checking platform ... (cached) linux [ubuntu]
checking for C compiler ... (cached) gcc
checking if gcc works ... yes
checking if gcc accepts '-x c -std=gnu17 -Wall -pedantic' ... yes
checking for ar ... (cached) ar
checking for rpc ... no
checking complex support ... yes
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib/X11
checking for OpenGL ... yes
checking for sfpen ... (cached) xtpen
checking for ppm ... yes
checking for tiff ... yes
checking for GD (PNG) ... yes
checking for GD (GIF) ... yes
checking for plplot ... yes
checking for ffmpeg ... yes
checking for cairo (PNG) ... yes
checking for cairo (SVG) ... yes
checking for cairo (PDF) ... yes
checking for jpeg ... yes
checking for BLAS ... yes
checking for LAPACK ... yes
checking for SWIG ... (cached) /usr/bin/swig
checking for numpy ... (cached) yes
checking API options ... (cached) []
checking for C++ compiler ... (cached) g++
checking if g++ works ... yes
checking if g++ accepts '-std=gnu++17 -U__STRICT_ANSI__ -Wall -pedantic' ... yes
checking for MPICC ... (cached) /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi/bin/mpicc
checking if /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi/bin/mpicc works ... no

  Optional package: libopenmpi-dev
checking for MPICXX ... (cached) /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi/bin/mpicxx
checking if /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi/bin/mpicxx works ... no

  Optional package: libopenmpi-dev
checking for MPIRUN ... (cached) /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi/bin/mpirun
checking for Posix threads ... yes
checking for OpenMP ... yes
checking for CUDA ... (cached) /usr/local/cuda
checking if /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/bin/nvcc works ... yes
checking for FFTW ... yes
checking if FFTW supports threads ... yes
checking for SuiteSparse ... yes
scons: done reading SConscript files.
scons: Building targets ...
shell_script(["env.sh"], [])
shell_script(["env.csh"], [])
scons: done building targets.


```
2. `sudo make install`
```
Install file: "build/api/python/_c_m8r.so" as "/home/master/lib/python3.9/site-packages/_c_m8r.so"
/usr/bin/swig -o build/api/python/vplot_wrap.c -python build/api/python/vplot.i
gcc -o build/api/python/vplot_wrap.os -c -O2 -x c -std=gnu17 -Wall -pedantic -fopenmp -fPIC -Ibuild/include -I/home/master/anaconda3/lib/python3.9/site-packages/numpy/numarray/numpy -I/home/master/anaconda3/lib/python3.9/site-packages/numpy/core/include -I/home/master/anaconda3/include/python3.9 build/api/python/vplot_wrap.c
gcc -o build/api/python/_c_vplot.so -pthread -fopenmp -shared build/api/python/vplot_wrap.os -Lbuild/lib -ldrsfplot -ldrsf
Install file: "build/api/python/_c_vplot.so" as "/home/master/lib/python3.9/site-packages/_c_vplot.so"
Install file: "build/api/python/c_m8r.py" as "/home/master/lib/python3.9/site-packages/c_m8r.py"
Install file: "build/api/python/c_vplot.py" as "/home/master/lib/python3.9/site-packages/c_vplot.py"
Install file: "build/api/python/las.py" as "/home/master/lib/python3.9/site-packages/las.py"
__pycompile(["build/api/python/las.pyc"], ["build/api/python/las.py"])
Install file: "build/api/python/las.pyc" as "/home/master/lib/python3.9/site-packages/las.pyc"
Install file: "build/api/python/m8r.py" as "/home/master/lib/python3.9/site-packages/m8r.py"
Install file: "build/api/python/m8r.pyc" as "/home/master/lib/python3.9/site-packages/m8r.pyc"
Install file: "build/api/python/vplot.py" as "/home/master/lib/python3.9/site-packages/vplot.py"
__pycompile(["build/api/python/vplot.pyc"], ["build/api/python/vplot.py"])
Install file: "build/api/python/vplot.pyc" as "/home/master/lib/python3.9/site-packages/vplot.pyc"
Install file: "AUTHORS.txt" as "/home/master/share/doc/madagascar/AUTHORS.txt"
Install file: "COPYING.txt" as "/home/master/share/doc/madagascar/COPYING.txt"
Install file: "NEWS.txt" as "/home/master/share/doc/madagascar/NEWS.txt"
Install file: "README.md" as "/home/master/share/doc/madagascar/README.md"
/home/master/anaconda3/bin/python build/framework/rsf/sfdoc -w /home/master/share/doc/madagascar/html -r https://github.com/ahay/src/blob/madagascar-4.0 -v 4.0
Traceback (most recent call last):
  File "/home/master/Python/Madagascar/madagascar-4.0/build/framework/rsf/sfdoc", line 4, in <module>
    rsf.doc.cli()
  File "/home/master/lib/python3.9/site-packages/rsf/doc.py", line 1090, in cli
    import rsf.prog
  File "/home/master/lib/python3.9/site-packages/rsf/prog.py", line 14, in <module>
    import rsf.sfzone
ModuleNotFoundError: No module named 'rsf.sfzone'
scons: *** [/home/master/share/doc/madagascar/html/index.html] Error 1
scons: building terminated because of errors.
make: *** [Makefile:7: install] Error 2
```
Here is my **config.log**

**Expected behavior**
Oddly enough, the mistake I made yesterday is different from the one I made today. My last mistake is  here #285 

**Screenshots**

No.

**Desktop (please complete the following information):**

- OS: Ubuntu 
 - Version [22.04]

**Additional context**

None

**Comment by zhangxiaoshuotttt** [comment]
I have partially solved the installation problem, and the specific methods are  here #285. In addition, I suggest that you, like me, who are new, install the relevant libraries in advance after scons-h, and basically you can install them correctly.
