### ISSUE TITLE
[BUG] ImportError: cannot import name 'operatorPrecedence' from 'pyparsing'

### ISSUE THREAD

**Issue by Sh-Fang** [ahay/src#291]
:bug:  Bug report

**Description of the bug**

When I use `import fdmod`, the system prompts: `ModuleNotFoundError: No module named 'fdmod'`, I see that if you replace `import fdmod` with `import rsf.recipes.fdmod as fdmod` it might work.

But when I use `import rsf.recipes.fdmod as fdmod`, the system prompts: `ImportError: cannot import name 'operatorPrecedence' from 'pyparsing'`

I searched for this problem online and found this issue：https://github.com/pyparsing/pyparsing/issues/327#issuecomment-957868967

It says: _`operatorPrecedence` was renamed to `infixNotation` in version 1.5.7_

Should I change all references to `operatorPrecedence` to `infixNotation` ?

I also tried to change these to `infixNotation` later, but this leads to more errors.

I also tried downgrading `pyparsing` to a version prior to 1.5.7 which is 1.5.6, but again, this leads to more problems.

**To Reproduce**

1. shell execute `python`
2. `>>>import rsf.recipes.fdmod as fdmod`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/rsf/recipes/fdmod.py", line 3, in <module>
    import pplot,math
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/pplot/__init__.py", line 7, in <module>
    from pexdoc.ptypes import real_num, positive_real_num, offset_range, function
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/pexdoc/__init__.py", line 10, in <module>
    from .pcontracts import *
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/pexdoc/pcontracts.py", line 21, in <module>
    import contracts
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/__init__.py", line 44, in <module>
    from .useful_contracts import *
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/useful_contracts/__init__.py", line 8, in <module>
    from .numpy_specific import *    
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/useful_contracts/numpy_specific.py", line 7, in <module>
    @new_contract
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/__init__.py", line 28, in new_contract
    return new_contract_main(*args)
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/main.py", line 553, in new_contract
    new_contract_impl(identifier, function)
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/main.py", line 563, in new_contract_impl
    from .syntax import ParseException
  File "/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/contracts/syntax.py", line 6, in <module>
    from pyparsing import (delimitedList, Forward, Literal,
ImportError: cannot import name 'operatorPrecedence' from 'pyparsing' (/home/sheng/anaconda3/envs/mada/lib/python3.7/site-packages/pyparsing/__init__.py)
```

**Desktop (please complete the following information):**

- OS: [WSL：Ubuntu 20.04 LTS ]
 - Version [20.04]

**Additional context**

When I execute `from rsf.proj import *`, it is normal and no error (like this).

![image](https://user-images.githubusercontent.com/46022639/235087575-b40c962f-7226-411c-8ff6-6e2774c8d775.png)

**Comment by sfomel** [comment]
Thank you for reporting this bug.

Fixed here: https://github.com/ahay/src/commit/7d9c317ea7f7d88cc8597ca3c948422c8444ddb4
