### ISSUE TITLE
[BUG] error while running make install

### ISSUE THREAD

**Issue by Bonaaaa** [ahay/src#312]
:bug:  Bug report

I am trying to install Madagascar and reaching step to make install, but the process cancelled with information [makeandmakeinstall.txt](https://github.com/user-attachments/files/17715169/makeandmakeinstall.txt). Before this step, running "./configure" identify what installed or not on my system
[configoutput.txt](https://github.com/user-attachments/files/17714984/configoutput.txt)

**To Reproduce**

1. run " ./configure --prefix=/directory/where/madagascar/installed/"
2. run "make"
3. run "make install"

**Expected behavior**

install should be done without error

**Screenshots**

Should not be necessary as this is script problem

**Desktop (please complete the following information):**

- OS: Windows 11 using VMWare Workstation 17 with Ubuntu 24.04.1 OS

**Comment by Bonaaaa** [comment]
turned out there is some output not recorded in ./configure output text:
-------------------------------------------------------------------------------------------------------------
scons: *** [env.sh] ModuleNotFoundError : No module named 'imp'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/SCons/Action.py", line 1310, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bona/madagascar-4.0.1/madagascar-4.0/framework/setenv.py", line 61, in shell_script
    import imp
ModuleNotFoundError: No module named 'imp'
---------------------------------------------------------------------------------------------------------------
here is the full text after inserting output above : [configoutputinsert.txt](https://github.com/user-attachments/files/17716186/configoutputinsert.txt)

**Comment by Bonaaaa** [comment]
it turned out the module imp removed since python v3.12 and replace by importlib. But, setenv.py code in $RSFROOT/madagascar-4.0/framework/ folder that available to download under stable version on the website (https://ahay.org/wiki/Download) until now still using imp, causing this problem (it fixed on current development version, though).

the problem on setenv.py code in stable version:
-------------------------------------------------------------------------
import configure
import imp
config = imp.load_source('config', 'config.py')
----------------------------------------------------------------
fix (taken from [current development version code](https://github.com/ahay/src/blob/master/framework/setenv.py)):
-----------------------------------------------------------------------
  import configure

    if sys.version_info[0] == 3 and sys.version_info[1] >= 5:
        import importlib.util
        spec = importlib.util.spec_from_file_location('config', 'config.py')
        config = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(config)
    elif sys.version_info[0] == 3 and sys.version_info[1] < 5:
        import importlib.machinery
        loader = importlib.machinery.SourceFileLoader('config', 'config.py')
        config = loader.load_module()
    elif sys.version_info[0] == 2:
        import imp
        config = imp.load_source('config', 'config.py')
--------------------------------------------------------------------------------------
